# Generated by Django 4.2 on 2023-04-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='carrera',
            field=models.IntegerField(choices=[[0, 'Matematica'], [1, 'Fisica']], null=True),
        ),
    ]
