# Generated by Django 4.2 on 2023-04-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_alter_perfil_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.IntegerField(choices=[[0, 'Masculino'], [1, 'Femenino']], null=True),
        ),
    ]
