# Generated by Django 4.2 on 2023-05-09 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='archivo',
            name='tabla',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['p2'])]),
        ),
    ]
