# Generated by Django 4.2 on 2023-05-09 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_delete_post_alter_archivo_tabla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='tabla',
            new_name='file',
        ),
    ]
